<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
$GLOBALS['E_RankType'] = array(
  'ByDefault' => 1,
  'ByComment' => 2,
  'ByShare' => 3,
);

final class RankType {
  const ByDefault = 1;
  const ByComment = 2;
  const ByShare = 3;
  static public $__names = array(
    1 => 'ByDefault',
    2 => 'ByComment',
    3 => 'ByShare',
  );
}


