<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once __DIR__ . '/comment_score_types.php';

interface cmt_comment_scoreIf {
  public function score_batch($comments);
  public function score($comment);
}

class cmt_comment_scoreClient implements cmt_comment_scoreIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function score_batch($comments)
  {
    $this->send_score_batch($comments);
    return $this->recv_score_batch();
  }

  public function send_score_batch($comments)
  {
    $args = new cmt_comment_score_score_batch_args();
    $args->comments = $comments;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'score_batch', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $buff = pack('N', (0x80010000 | TMessageType::CALL));
      $buff .= pack('N', strlen('score_batch'));
      $buff .= 'score_batch';
      $buff .= pack('N', $this->seqid_);
      $args->write($buff);
      $this->output_->write($buff);
      $this->output_->flush();
    }
  }

  public function recv_score_batch()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'cmt_comment_score_score_batch_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $ver = unpack('N', $this->input_->readAll(4));
      $ver = $ver[1];
      $mtype = $ver & 0xff;
      $ver = $ver & 0xffff0000;
      if ($ver != 0x80010000) throw new TProtocolException('Bad version identifier: '.$ver, TProtocolException::BAD_VERSION);
      $len = unpack('N', $this->input_->readAll(4));
      $len = $len[1];
      if ($len > 0x7fffffff) {
        $len = 0 - (($len - 1) ^ 0xffffffff);
      }
      $fname = $this->input_->readAll($len);
      $val = unpack('N', $this->input_->readAll(4));
      $val = $val[1];
      if ($val > 0x7fffffff) {
        $val = 0 - (($val - 1) ^ 0xffffffff);
      }
      $rseqid = $val;
      $result = new cmt_comment_score_score_batch_result();
      $result->read($this->input_);
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("score_batch failed: unknown result");
  }

  public function score($comment)
  {
    $this->send_score($comment);
    return $this->recv_score();
  }

  public function send_score($comment)
  {
    $args = new cmt_comment_score_score_args();
    $args->comment = $comment;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'score', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $buff = pack('N', (0x80010000 | TMessageType::CALL));
      $buff .= pack('N', strlen('score'));
      $buff .= 'score';
      $buff .= pack('N', $this->seqid_);
      $args->write($buff);
      $this->output_->write($buff);
      $this->output_->flush();
    }
  }

  public function recv_score()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, 'cmt_comment_score_score_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $ver = unpack('N', $this->input_->readAll(4));
      $ver = $ver[1];
      $mtype = $ver & 0xff;
      $ver = $ver & 0xffff0000;
      if ($ver != 0x80010000) throw new TProtocolException('Bad version identifier: '.$ver, TProtocolException::BAD_VERSION);
      $len = unpack('N', $this->input_->readAll(4));
      $len = $len[1];
      if ($len > 0x7fffffff) {
        $len = 0 - (($len - 1) ^ 0xffffffff);
      }
      $fname = $this->input_->readAll($len);
      $val = unpack('N', $this->input_->readAll(4));
      $val = $val[1];
      if ($val > 0x7fffffff) {
        $val = 0 - (($val - 1) ^ 0xffffffff);
      }
      $rseqid = $val;
      $result = new cmt_comment_score_score_result();
      $result->read($this->input_);
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new Exception("score failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class cmt_comment_score_score_batch_args {
  static $_TSPEC;

  public $comments = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'comments',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => 'cmt_CommentInfo',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['comments'])) {
        $this->comments = $vals['comments'];
      }
    }
  }

  public function getName() {
    return 'comment_score_score_batch_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    while (true)
    {
      $ftype = unpack('c', $input->readAll(1));
      $ftype = $ftype[1];
      if ($ftype == TType::STOP) {
        break;
      }
      $val = unpack('n', $input->readAll(2));
      $val = $val[1];
      if ($val > 0x7fff) {
        $val = 0 - (($val - 1) ^ 0xffff);
      }
      $fid = $val;
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::LST) {
            $this->comments = array();
            $_size7 = 0;
            $_etype10 = unpack('c', $input->readAll(1));
            $_etype10 = $_etype10[1];
            $val = unpack('N', $input->readAll(4));
            $val = $val[1];
            if ($val > 0x7fffffff) {
              $val = 0 - (($val - 1) ^ 0xffffffff);
            }
            $_size7 = $val;
            for ($_i11 = 0; $_i11 < $_size7; ++$_i11)
            {
              $elem12 = null;
              $elem12 = new cmt_CommentInfo();
              $xfer += $elem12->read($input);
              $this->comments []= $elem12;
            }
          } else {
            $xfer += TProtocol::skipBinary($input, $ftype);
          }
          break;
        default:
          $xfer += TProtocol::skipBinary($input, $ftype);
          break;
      }
    }
    return $xfer;
  }

  public function write(&$output) {
    $xfer = 0;
    if ($this->comments !== null) {
      if (!is_array($this->comments)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $output .= pack('c', TType::LST);
      $output .= pack('n', 1);
      {
        $output .= pack('c', TType::STRUCT);
        $output .= strrev(pack('l', count($this->comments)));
        {
          foreach ($this->comments as $iter13)
          {
            $xfer += $iter13->write($output);
          }
        }
      }
    }
    $output .= pack('c', TType::STOP);
    return $xfer;
  }

}

class cmt_comment_score_score_batch_result {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::LST,
          'etype' => TType::I32,
          'elem' => array(
            'type' => TType::I32,
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'comment_score_score_batch_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    while (true)
    {
      $ftype = unpack('c', $input->readAll(1));
      $ftype = $ftype[1];
      if ($ftype == TType::STOP) {
        break;
      }
      $val = unpack('n', $input->readAll(2));
      $val = $val[1];
      if ($val > 0x7fff) {
        $val = 0 - (($val - 1) ^ 0xffff);
      }
      $fid = $val;
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::LST) {
            $this->success = array();
            $_size14 = 0;
            $_etype17 = unpack('c', $input->readAll(1));
            $_etype17 = $_etype17[1];
            $val = unpack('N', $input->readAll(4));
            $val = $val[1];
            if ($val > 0x7fffffff) {
              $val = 0 - (($val - 1) ^ 0xffffffff);
            }
            $_size14 = $val;
            for ($_i18 = 0; $_i18 < $_size14; ++$_i18)
            {
              $elem19 = null;
              $val = unpack('N', $input->readAll(4));
              $val = $val[1];
              if ($val > 0x7fffffff) {
                $val = 0 - (($val - 1) ^ 0xffffffff);
              }
              $elem19 = $val;
              $this->success []= $elem19;
            }
          } else {
            $xfer += TProtocol::skipBinary($input, $ftype);
          }
          break;
        default:
          $xfer += TProtocol::skipBinary($input, $ftype);
          break;
      }
    }
    return $xfer;
  }

  public function write(&$output) {
    $xfer = 0;
    if ($this->success !== null) {
      if (!is_array($this->success)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $output .= pack('c', TType::LST);
      $output .= pack('n', 0);
      {
        $output .= pack('c', TType::I32);
        $output .= strrev(pack('l', count($this->success)));
        {
          foreach ($this->success as $iter20)
          {
            $output .= pack('N', $iter20);
          }
        }
      }
    }
    $output .= pack('c', TType::STOP);
    return $xfer;
  }

}

class cmt_comment_score_score_args {
  static $_TSPEC;

  public $comment = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'comment',
          'type' => TType::STRUCT,
          'class' => 'cmt_CommentInfo',
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['comment'])) {
        $this->comment = $vals['comment'];
      }
    }
  }

  public function getName() {
    return 'comment_score_score_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    while (true)
    {
      $ftype = unpack('c', $input->readAll(1));
      $ftype = $ftype[1];
      if ($ftype == TType::STOP) {
        break;
      }
      $val = unpack('n', $input->readAll(2));
      $val = $val[1];
      if ($val > 0x7fff) {
        $val = 0 - (($val - 1) ^ 0xffff);
      }
      $fid = $val;
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->comment = new cmt_CommentInfo();
            $xfer += $this->comment->read($input);
          } else {
            $xfer += TProtocol::skipBinary($input, $ftype);
          }
          break;
        default:
          $xfer += TProtocol::skipBinary($input, $ftype);
          break;
      }
    }
    return $xfer;
  }

  public function write(&$output) {
    $xfer = 0;
    if ($this->comment !== null) {
      if (!is_object($this->comment)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $output .= pack('c', TType::STRUCT);
      $output .= pack('n', 1);
      $xfer += $this->comment->write($output);
    }
    $output .= pack('c', TType::STOP);
    return $xfer;
  }

}

class cmt_comment_score_score_result {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['success'])) {
        $this->success = $vals['success'];
      }
    }
  }

  public function getName() {
    return 'comment_score_score_result';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    while (true)
    {
      $ftype = unpack('c', $input->readAll(1));
      $ftype = $ftype[1];
      if ($ftype == TType::STOP) {
        break;
      }
      $val = unpack('n', $input->readAll(2));
      $val = $val[1];
      if ($val > 0x7fff) {
        $val = 0 - (($val - 1) ^ 0xffff);
      }
      $fid = $val;
      switch ($fid)
      {
        case 0:
          if ($ftype == TType::I32) {
            $val = unpack('N', $input->readAll(4));
            $val = $val[1];
            if ($val > 0x7fffffff) {
              $val = 0 - (($val - 1) ^ 0xffffffff);
            }
            $this->success = $val;
          } else {
            $xfer += TProtocol::skipBinary($input, $ftype);
          }
          break;
        default:
          $xfer += TProtocol::skipBinary($input, $ftype);
          break;
      }
    }
    return $xfer;
  }

  public function write(&$output) {
    $xfer = 0;
    if ($this->success !== null) {
      $output .= pack('c', TType::I32);
      $output .= pack('n', 0);
      $output .= pack('N', $this->success);
    }
    $output .= pack('c', TType::STOP);
    return $xfer;
  }

}
