<div id="ft">
    <p><a href="<%#siteUrl#%>/copyright" target="_blank">免责声明</a> | <a href="mailto:quanloo@snda.com">用户反馈</a> | <a href="/links">友情链接</a></p>
    <p style="text-indent:46px">沪ICP备10212628号-30 © 2012&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;盛乐信息技术（上海）有限公司版权所有</p>
    <p style="text-align:center;margin-top:10px;"><a target="_blank" href="http://www.shjubao.cn/"><img src="<%#resUrl#%>/img/foot_ico.png"></a></p>
</div>