    	<div id="hd">
        	<div class="wrap">
            	<div class="content">
                    <div id="logo">
                        <a href="<%#siteUrl#%>/" title="首页">
                            <img src="<%#resUrl#%>/img/logo.png?20120823" alt="圈乐" />
                        </a>
                    </div>
                    <%include file="inc/_header_search.inc" inline%>                   
                </div>
            </div>
        </div>
        <div class="black-tips"><span>提示</span><em></em></i></div>
        
        <%include file="inc/_header_login.inc" inline%>
        <%include file="inc/brick_tmpl.inc"  inline%>

    <a href="###" id="feed_back" class="marmot" data--marmot="{page_id:'click_feedback'}"><img src="<%#resUrl#%>/img/feedback.png"></a>
