<div class="panel panel-t1" style="width:429px;display:none" id="sns_share_popup">
</div>
<div class="panel panel-t1" style="width:429px;display:none" id="sns_share_succ_popup">
	<div class="panel-content">
		<div class="hd">
			<h3>分享成功</h3>
		</div>
		<div class="bd">
			<div class="panel-bind-res">
				<p class="status s-ok">已成功分享给好友，3秒后自动关闭。</p>
				<div class="btns clearfix">
					<a href="###" class="bt-ok close__">确定</a>
				</div>
			</div>
		</div>
		<div class="ft"></div>
	</div>
	<span class="close close__"></span>	

</div>

<div class="panel panel-t1" style="width:429px;display:none" id="sns_bind_popup">
	<div class="panel-content">
		<div class="hd">
			<h3>帐号绑定</h3>
		</div>
		<div class="bd">
			<div class="panel-bind-check">
				<p class="bindtype bindtype-sina" type="2">前往新浪微博连接帐号，圈乐会保证你的帐号安全，请放心绑定...</p>
				<p class="bindtype bindtype-tqq" type="3">前往腾讯微博连接帐号，圈乐会保证你的帐号安全，请放心绑定...</p>
				<div class="btns">
					<a class="isok" href="###">完成绑定</a>还未绑定?请<a class="retry" href="#">重新连接</a> 
				</div>
			</div>
		</div>
		<div class="ft"></div>
	</div>
	<span class="close close__"></span>
</div>
<div class="panel panel-t1 sns-bind-err" style="width:429px;display:none" id="sns_bind_err_popup">
	<div class="panel-content">
		<div class="hd">
			<h3>帐号绑定</h3>
		</div>
		<div class="bd">
			<div class="panel-bind-res">
				<p class="status s-err">绑定失败请重新绑定，如果问题还是存在，可能是相关平台繁忙，请稍后重试。</p>
				<div class="btns clearfix">
					<a href="###" class="bt-ok close__">确定</a>
				</div>
			</div>
		</div>
		<div class="ft"></div>
	</div>
	<span class="close close__"></span>
</div>
<div class="share-bind-tips">
	<div class="text"></div>
	<span class="cur"></span>
</div>